-- GENERATED by scripts/db-grants.mjs from nfrvxkwemtittrqboebl on 2026-07-27.
-- Do not edit by hand; re-run `npm run db:grants` after changing privileges.
--
-- Apply AFTER scripts/sql/schema.sql when building a database. See the header
-- of scripts/db-grants.mjs for why schema.sql alone is not sufficient.

-- 1. Start from nothing, so the target's default privileges cannot leak through.
revoke all on table "public"."av_roles" from anon, authenticated;
revoke all on table "public"."crew_members" from anon, authenticated;
revoke all on table "public"."crew_rate_cards_visible" from anon, authenticated;
revoke all on table "public"."invitations" from anon, authenticated;
revoke all on table "public"."organizations" from anon, authenticated;
revoke all on table "public"."payroll_presets" from anon, authenticated;
revoke all on table "public"."payroll_rulesets" from anon, authenticated;
revoke all on table "public"."profiles" from anon, authenticated;
revoke all on table "public"."punches" from anon, authenticated;
revoke all on table "public"."rate_cards" from anon, authenticated;
revoke all on table "public"."rooms" from anon, authenticated;
revoke all on table "public"."show_assignments" from anon, authenticated;
revoke all on table "public"."shows" from anon, authenticated;
revoke all on table "public"."subscriptions" from anon, authenticated;
revoke all on table "public"."timecard_day_rates" from anon, authenticated;
revoke all on table "public"."timecards" from anon, authenticated;
revoke all on table "public"."work_days" from anon, authenticated;

-- 2. Table-level privileges, exactly as held in nfrvxkwemtittrqboebl.
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."av_roles" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."av_roles" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."crew_members" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."crew_members" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."crew_rate_cards_visible" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."invitations" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."invitations" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."organizations" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."organizations" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."payroll_presets" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."payroll_presets" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."payroll_rulesets" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."payroll_rulesets" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."profiles" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."profiles" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."punches" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."punches" to authenticated;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."rate_cards" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."rooms" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."rooms" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."show_assignments" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."show_assignments" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."shows" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."shows" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."subscriptions" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."subscriptions" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."timecard_day_rates" to authenticated;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."timecards" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."work_days" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."work_days" to authenticated;

-- 3. Column-level privileges. The absence of a column here is deliberate and
--    load-bearing: day_rate is withheld from authenticated on timecards and
--    rate_cards, and reads route through the SECURITY DEFINER views instead.
grant SELECT("id") on table "public"."rate_cards" to authenticated;
grant SELECT("crew_member_id") on table "public"."rate_cards" to authenticated;
grant SELECT("role") on table "public"."rate_cards" to authenticated;
grant SELECT("created_at") on table "public"."rate_cards" to authenticated;
grant SELECT("id") on table "public"."timecards" to authenticated;
grant SELECT("room_id") on table "public"."timecards" to authenticated;
grant SELECT("crew_member_id") on table "public"."timecards" to authenticated;
grant SELECT("crew_member_name") on table "public"."timecards" to authenticated;
grant SELECT("role") on table "public"."timecards" to authenticated;
grant SELECT("is_travel_day") on table "public"."timecards" to authenticated;
grant SELECT("travel_in_day") on table "public"."timecards" to authenticated;
grant SELECT("travel_out_day") on table "public"."timecards" to authenticated;
grant SELECT("pay_as_half_day") on table "public"."timecards" to authenticated;
grant SELECT("created_at") on table "public"."timecards" to authenticated;
grant SELECT("updated_at") on table "public"."timecards" to authenticated;
