// Generate scripts/sql/grants.sql — the exact anon/authenticated privileges,
// written as REVOKE-then-GRANT so a rebuild lands on the same state every time.
//
//   npm run db:grants        read production, rewrite scripts/sql/grants.sql
//
// WHY THIS EXISTS
// ---------------
// pg_dump expresses privileges as GRANTs only. It computes them against
// Postgres's built-in default (owner holds everything, nobody else holds
// anything), so a privilege that was REVOKED is represented as an *absence* —
// there is simply no GRANT line for it. That is fine when restoring into an
// empty cluster, and wrong on Supabase, where ALTER DEFAULT PRIVILEGES hands
// every newly created table to anon and authenticated before the dump's grants
// are applied. Anything the dump does not mention is not removed; it is
// inherited. Two real examples, both caught comparing crewtracker-dev to
// production:
//
//   * timecards.day_rate / rate_cards.day_rate — the B2 lockdown is "grant every
//     other column by name and never mention day_rate". With the default ACL
//     active, day_rate comes back readable to every signed-in user.
//   * anon on timecards / rate_cards — revoked outright in production, but the
//     default ACL re-granted TRUNCATE, REFERENCES and TRIGGER in dev.
//
// So schema.sql alone does not reproduce the security posture. Applying this
// file after it does, because it revokes first and then grants exactly what
// production holds — no reliance on what the target happened to start with.
//
// Reads pg_class.relacl and pg_attribute.attacl (the *explicit* ACLs) rather
// than information_schema.column_privileges, which also reports column
// privileges merely implied by a table-level grant and would emit thousands of
// redundant lines.

import pg from 'pg'
import { writeFileSync } from 'node:fs'

const ROLES = ['anon', 'authenticated']
// Postgres ACL letters -> privilege names. 'm' (MAINTAIN) is PG17+.
const PRIV = { r:'SELECT', a:'INSERT', w:'UPDATE', d:'DELETE', D:'TRUNCATE', x:'REFERENCES', t:'TRIGGER', m:'MAINTAIN' }

const fromDev = process.argv.includes('--from-dev')
const url = fromDev ? process.env.DATABASE_URL : process.env.DATABASE_URL_PROD
if (!url) {
  console.error(`${fromDev ? 'DATABASE_URL' : 'DATABASE_URL_PROD'} is not set.`)
  process.exit(1)
}

// aclitem renders as "grantee=privs/grantor"; privs may carry '*' (grant option).
function privsFor(aclArray, role) {
  for (const item of aclArray ?? []) {
    const [grantee, rest] = String(item).split('=')
    if (grantee !== role) continue
    const letters = (rest ?? '').split('/')[0].replace(/\*/g, '')
    return [...letters].map((l) => PRIV[l]).filter(Boolean)
  }
  return []
}

const client = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } })
await client.connect()

const ref = (url.match(/postgres\.([a-z0-9]+)/) || [])[1] ?? 'unknown'

const { rows: rels } = await client.query(`
  select c.relname, c.relkind, c.relacl::text[] as acl
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r','v','m')
  order by c.relname`)

const { rows: cols } = await client.query(`
  select c.relname, a.attname, a.attacl::text[] as acl
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and a.attacl is not null and a.attnum > 0
  order by c.relname, a.attnum`)

await client.end()

const L = [
  `-- GENERATED by scripts/db-grants.mjs from ${ref} on ${new Date().toISOString().slice(0,10)}.`,
  `-- Do not edit by hand; re-run \`npm run db:grants\` after changing privileges.`,
  `--`,
  `-- Apply AFTER scripts/sql/schema.sql when building a database. See the header`,
  `-- of scripts/db-grants.mjs for why schema.sql alone is not sufficient.`,
  ``,
]

L.push(`-- 1. Start from nothing, so the target's default privileges cannot leak through.`)
for (const r of rels) L.push(`revoke all on table "public"."${r.relname}" from ${ROLES.join(', ')};`)

L.push(``, `-- 2. Table-level privileges, exactly as held in ${ref}.`)
for (const r of rels) {
  for (const role of ROLES) {
    const p = privsFor(r.acl, role)
    if (p.length) L.push(`grant ${p.join(', ')} on table "public"."${r.relname}" to ${role};`)
  }
}

L.push(``, `-- 3. Column-level privileges. The absence of a column here is deliberate and`, `--    load-bearing: day_rate is withheld from authenticated on timecards and`, `--    rate_cards, and reads route through the SECURITY DEFINER views instead.`)
for (const c of cols) {
  for (const role of ROLES) {
    const p = privsFor(c.acl, role)
    if (p.length) L.push(`grant ${p.map((x) => `${x}("${c.attname}")`).join(', ')} on table "public"."${c.relname}" to ${role};`)
  }
}

L.push(``)
writeFileSync('scripts/sql/grants.sql', L.join('\n'))

const tableGrants = L.filter((l) => l.startsWith('grant') && !l.includes('(')).length
const colGrants = L.filter((l) => l.startsWith('grant') && l.includes('(')).length
console.log(`Read ${ref}: ${rels.length} relations, ${cols.length} column ACLs`)
console.log(`Wrote scripts/sql/grants.sql — ${rels.length} revokes, ${tableGrants} table grants, ${colGrants} column grants`)
